# Generated by Django 5.2 on 2025-05-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principala', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='increderesursa',
            name='bias',
            field=models.CharField(choices=[('stanga', 'Inclinari de stanga'), ('dreapta', 'Inclinari de dreapta'), ('fdreapta', 'Inclinari puternica dreapta'), ('fstanga', 'Inclinari puternice stanga'), ('centru', 'Neutru')], max_length=20),
        ),
    ]
