# Generated by Django 5.2 on 2025-05-05 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principala', '0003_alter_increderesursa_bias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comentariu_user',
            new_name='feedback_user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='este_corecta',
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.TextField(default='fara_email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='nume',
            field=models.TextField(default='fara_nume'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='analiza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina_principala.rezultatanaliza'),
        ),
    ]
