# Generated by Django 5.2 on 2025-04-30 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncredereSursa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('scor_incredere', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('bias', models.CharField(choices=[('stanga', 'Inclinari de stanga'), ('dreapta', 'Inclinari de dreapta'), ('centru', 'Neutru')], max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RezultatAnaliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('sentiment', models.JSONField(blank=True, null=True)),
                ('veridicitate', models.JSONField(blank=True, null=True)),
                ('verificare_sursa', models.JSONField(blank=True, null=True)),
                ('articole_similare', models.JSONField(blank=True, null=True)),
                ('sursa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagina_principala.increderesursa')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('este_corecta', models.BooleanField()),
                ('comentariu_user', models.TextField(blank=True)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('analiza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_principala.rezultatanaliza')),
            ],
        ),
    ]
