# Generated by Django 5.2 on 2025-05-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principala', '0004_rename_comentariu_user_feedback_feedback_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='nume',
            field=models.CharField(max_length=200),
        ),
    ]
