# Generated by Django 5.2 on 2025-05-05 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principala', '0005_alter_feedback_email_alter_feedback_nume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='analiza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina_principala.rezultatanaliza'),
        ),
    ]
