# Generated by Django 5.2.3 on 2025-06-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principala', '0007_globalconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfig',
            name='threshold',
            field=models.FloatField(default=0.5, help_text='Threshold pentru a defini procentul la care o sursa este considerata FAKE/REAL.'),
        ),
    ]
