# Generated by Django 5.2.3 on 2025-06-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principala', '0008_alter_globalconfig_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalThreshold',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('threshold', models.FloatField(default=0.5, help_text='Threshold pentru a defini procentul la care o sursa este considerata FAKE/REALA')),
            ],
            options={
                'verbose_name': 'Global Threshold',
            },
        ),
        migrations.DeleteModel(
            name='GlobalConfig',
        ),
    ]
