# Generated by Django 5.2.3 on 2025-06-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principala', '0009_globalthreshold_delete_globalconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllsidesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_source', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=255)),
                ('rating_num', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('agree', models.CharField(max_length=255)),
                ('disagree', models.CharField(max_length=255)),
                ('perc_agree', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('editorial_review', models.CharField(max_length=255)),
                ('blind_survey', models.CharField(max_length=255)),
                ('third_party_analysis', models.CharField(max_length=255)),
                ('independent_research', models.CharField(max_length=255)),
                ('confidence_level', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('wiki', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('screen_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pagina_principala_allsides_data',
                'managed': False,
            },
        ),
    ]
