# Generated by Django 5.2.3 on 2025-06-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principala', '0010_allsidesdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnigramFreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('count', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pagina_principala_unigram_freq',
                'managed': False,
            },
        ),
    ]
