# Generated by Django 5.2.3 on 2025-06-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_principala', '0011_unigramfreq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
